### ISSUE TITLE
Include dataset names in log messages

### ISSUE THREAD

**Issue by stuarteberg** [connectome-neuprint/neuPrintHTTP#51] opened 2021-04-07 17:23 UTC
In the log, the neuprint dataset (hemibrain vs vnc) isn't mentioned.  It would be nice to include that, so we know which datasets have been accessed most heavily.

**Comment by stuarteberg** [comment] 2024-04-12 15:29
@DocSavage Is this something you could do?  We'll also be making other minor updates to neuprintHTTP soon.

**Comment by neomorphic** [comment] 2024-04-12 18:36
duplicate of #63

**Closed by neomorphic** 2024-04-12 18:36 UTC
Labels: enhancement
